### ISSUE TITLE
Error encountered resolving symbol values statically. Could not resolve angular2-autosize relative to <locatiation of app.module.ts>

### ISSUE THREAD

**Issue by jjmurre** [stevepapa/angular2-autosize#26]
Getting this error since @angular-cli/1.0.1

After changing the import from (as suggested in the readme):
import { Autosize } from 'angular2-autosize'
to:
import { Autosize } from 'angular2-autosize/angular2-autosize'
The error disappears.

**Comment by shoudaos** [comment]
+1

**Comment by vishnunair17** [comment]
+1

**Comment by fahdsaeed** [comment]
can someone help 

ERROR in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts (5,30): Cannot find module 'angular2-select'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve angular2-select relative to /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts., resolving symbol DashboardModule in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts, resolving symbol DashboardModule in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts
    at Error (native)
    at syntaxError (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

webpack: Failed to compile.


i get this error
